# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

archives:
  - id: default
    builds:
      - deep

builds:
  - id: deep
    main: ./cmd/deep
    binary: deep
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    flags:
      - -v
      - -trimpath
    ldflags:
      - -X main.Branch={{ .Branch }}
      - -X main.Revision={{ .ShortCommit }}
      - -X main.Version={{ .Version }}

kos:
  - id: deep
    main: ./cmd/deep
    env:
      - CGO_ENABLED=0
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - -v
      - -trimpath
    ldflags:
      - -X main.Branch={{ .Branch }}
      - -X main.Revision={{ .ShortCommit }}
      - -X main.Version={{ .Version }}
    repository: bendonnelly
    tags:
      - latest
      - '{{.Version}}'
    base_import_paths: true

checksum:
  name_template: SHA256SUMS

changelog:
  disable: true

release:
  prerelease: auto
