version: "3"
services:

  distributor:
    image: intergral/deep:latest
    command: "-target=distributor -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep
      - "43315" # deep grpc ingest

  ingester-0:
    image: intergral/deep:latest
    command: "-target=ingester -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  ingester-1:
    image: intergral/deep:latest
    command: "-target=ingester -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  ingester-2:
    image: intergral/deep:latest
    command: "-target=ingester -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  query-frontend:
    image: intergral/deep:latest
    command: "-target=query-frontend -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300:3300"   # deep

  querier:
    image: intergral/deep:latest
    command: "-target=querier -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  compactor:
    image: intergral/deep:latest
    command: "-target=compactor -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  metrics-generator:
    image: intergral/deep:latest
    command: "-target=metrics-generator -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  tracepoint:
    image: intergral/deep:latest
    command: "-target=tracepoint -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300" #deep

  tracepoint-api:
    image: intergral/deep:latest
    command: "-target=tracepoint-api -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    ports:
      - "3300" #deep
    depends_on:
      - minio


  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=deep
      - MINIO_SECRET_KEY=supersecret
    ports:
      - "9001:9001"
    entrypoint:
      - sh
      - -euc
      - mkdir -p /data/deep && minio server /data --console-address ':9001'

  test_app:
    image: intergral/deep-python:latest
    environment:
      - DEEP_SERVICE_URL=distributor:43315
      - DEEP_SERVICE_SECURE=False
    depends_on:
      - distributor

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: intergral/grafana-deep:D0.0.5P0.0.3
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
