global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'deep'
    static_configs:
      - targets:
        - 'compactor:3300'
        - 'distributor:3300'
        - 'ingester-0:3300'
        - 'ingester-1:3300'
        - 'ingester-2:3300'
        - 'querier:3300'
        - 'query-frontend:3300'
        - 'metrics-generator:3300'
        - 'tracepoint:3300'
