server:
  http_listen_port: 3300
  grpc_listen_port: 43315
  log_level: debug

distributor:
  receivers:
    deep:
  log_received_snapshots:
    enabled: true
    include_all_attributes: true

ingester:
  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

compactor:
  compaction:
    block_retention: 1h                # overall Deep snapshot retention. set for demo purposes

metrics_generator:
  registry:
    external_labels:
      source: deep
      cluster: docker-compose
  storage:
    path: /tmp/deep/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

use_otel_tracer: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /tmp/deep/wal             # where to store the the wal locally
    local:
      path: /tmp/deep/blocks

overrides:
  metrics_generator_processors: [span-metrics] # enables metrics generator
