version: "3"
services:

  deep:
    image: intergral/deep:latest
    command: [ "-config.file=/etc/deep.yaml" ]
    volumes:
      - ./deep-s3.yaml:/etc/deep.yaml
      - ./deep-data:/tmp/deep
    restart: on-failure
    depends_on:
      - minio
    ports:
      - "3300:3300"   # deep http
      - "43315:43315"   # deep grpc

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=deep
      - MINIO_SECRET_KEY=supersecret
    ports:
      - "9001:9001"
    entrypoint:
      - sh
      - -euc
      - mkdir -p /data/deep && /opt/bin/minio server /data --console-address ':9001'

  test_app:
    image: intergral/deep-python:latest
    environment:
      - DEEP_SERVICE_SECURE=False
    depends_on:
      - deep

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ../shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: ghcr.io/intergral/grafana:deep
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
