version: "3"
services:

  deep:
    image: intergral/deep-debug:latest
    command: [ "-config.file=/etc/deep.yaml" ]
    volumes:
      - ../shared/deep.yaml:/etc/deep.yaml
      - ./deep-data:/tmp/deep
    environment:
      - DEBUG_BLOCK=0
    ports:
      - "3300:3300"   # deep http
      - "43315:43315"   # deep grpc
      - "2345:2345"   # delve debug server

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ../shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../shared/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=https://github.com/intergral/grafana-deep-panel/releases/download/v0.0.3/intergral-deep-panel-0.0.3.zip;intergral-deep-panel,https://github.com/intergral/grafana-deep-datasource/releases/download/v0.0.7/intergral-deep-datasource-0.0.7.zip;intergral-deep-datasource
    ports:
      - "3000:3000"

  test_app:
    image: intergral/deep-python:latest
    environment:
      - DEEP_SERVICE_SECURE=False
    depends_on:
      - deep
