version: "3"
services:

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../shared/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://tempo:14268/api/traces
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  deep:
    image: deep/deep-debug:latest
    command: [ "-config.file=/etc/deep.yaml" ]
    volumes:
      - ../shared/deep.yaml:/etc/deep.yaml
      - ./deep-data:/tmp/deep
    environment:
      - DEBUG_BLOCK=0
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://tempo:14268/api/traces
    ports:
      - "3300:3300"   # deep http
      - "43315:43315"   # deep grpc
      - "2345:2345"   # delve debug server

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ../shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../shared/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"


  test_app:
    image: ghcr.io/intergral/deep-python-client:simple-app
    environment:
      - DEEP_SERVICE_SECURE=False
      - DEEP_LOGGING_CONF=/etc/client_logging.conf
    volumes:
      - ../shared/client_logging.conf:/etc/client_logging.conf
    depends_on:
      - deep