site_name: Deep
site_url: https://intergral.github.com/deep/

repo_name: Deep
repo_url: https://github.com/intergral/deep

site_dir: _site

copyright: Intergral GmbH 2023

theme:
  name: material
  features:
    - content.code.copy

#extra_css:
#  - styles/styles.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - glightbox:
