name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: make test-with-cover

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Build Deep
        run: make deep

      - name: Build deep-cli
        run: make deep-cli

  vendor-check:
    name: Vendor check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.11.2'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check vendor
        run: make vendor-check
