name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Test
        run: make test-with-cover-report

      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: GO Tests
          path: report.xml
          reporter: java-junit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Vendor
        run: go mod vendor

      - name: Build Deep
        run: make deep

      - name: Build deep-cli
        run: make deep-cli

  vendor-check:
    name: Vendor check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.11.2'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check vendor
        run: make vendor-check
