name: Release

on:
  release:
    types: [ published ]

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Vendor
        run: go mod vendor

      - name: Build
        run: make deep

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./bin/linux/deep-amd64"
          release_id: $VERSION

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build image
        run: make docker-deep-ci

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker tag intergral/deep intergral/deep:$VERSION
          docker tag intergral/deep intergral/deep:latest
          docker push intergral/deep:$VERSION
          docker push intergral/deep:latest


